# frozen_string_literal: true

module ColorSwatchCollection
  class Ntc
    def self.colours
      [
        { name: 'black', hex: '#000000' },
        { name: 'navy blue', hex: '#000080' },
        { name: 'dark blue', hex: '#0000C8' },
        { name: 'blue', hex: '#0000FF' },
        { name: 'stratos', hex: '#000741' },
        { name: 'swamp', hex: '#001B1C' },
        { name: 'resolution blue', hex: '#002387' },
        { name: 'deep fir', hex: '#002900' },
        { name: 'burnham', hex: '#002E20' },
        { name: 'international klein blue', hex: '#002FA7' },
        { name: 'prussian blue', hex: '#003153' },
        { name: 'midnight blue', hex: '#003366' },
        { name: 'smalt', hex: '#003399' },
        { name: 'deep teal', hex: '#003532' },
        { name: 'cyprus', hex: '#003E40' },
        { name: 'kaitoke green', hex: '#004620' },
        { name: 'cobalt', hex: '#0047AB' },
        { name: 'crusoe', hex: '#004816' },
        { name: 'sherpa blue', hex: '#004950' },
        { name: 'endeavour', hex: '#0056A7' },
        { name: 'camarone', hex: '#00581A' },
        { name: 'science blue', hex: '#0066CC' },
        { name: 'blue ribbon', hex: '#0066FF' },
        { name: 'tropical rain forest', hex: '#00755E' },
        { name: 'allports', hex: '#0076A3' },
        { name: 'deep cerulean', hex: '#007BA7' },
        { name: 'lochmara', hex: '#007EC7' },
        { name: 'azure radiance', hex: '#007FFF' },
        { name: 'teal', hex: '#008080' },
        { name: 'bondi blue', hex: '#0095B6' },
        { name: 'pacific blue', hex: '#009DC4' },
        { name: 'persian green', hex: '#00A693' },
        { name: 'jade', hex: '#00A86B' },
        { name: 'caribbean green', hex: '#00CC99' },
        { name: "robin's egg blue", hex: '#00CCCC' },
        { name: 'green', hex: '#00FF00' },
        { name: 'spring green', hex: '#00FF7F' },
        { name: 'cyan / aqua', hex: '#00FFFF' },
        { name: 'blue charcoal', hex: '#010D1A' },
        { name: 'midnight', hex: '#011635' },
        { name: 'holly', hex: '#011D13' },
        { name: 'daintree', hex: '#012731' },
        { name: 'cardin green', hex: '#01361C' },
        { name: 'county green', hex: '#01371A' },
        { name: 'astronaut blue', hex: '#013E62' },
        { name: 'regal blue', hex: '#013F6A' },
        { name: 'aqua deep', hex: '#014B43' },
        { name: 'orient', hex: '#015E85' },
        { name: 'blue stone', hex: '#016162' },
        { name: 'fun green', hex: '#016D39' },
        { name: 'pine green', hex: '#01796F' },
        { name: 'blue lagoon', hex: '#017987' },
        { name: 'deep sea', hex: '#01826B' },
        { name: 'green haze', hex: '#01A368' },
        { name: 'english holly', hex: '#022D15' },
        { name: 'sherwood green', hex: '#02402C' },
        { name: 'congress blue', hex: '#02478E' },
        { name: 'evening sea', hex: '#024E46' },
        { name: 'bahama blue', hex: '#026395' },
        { name: 'observatory', hex: '#02866F' },
        { name: 'cerulean', hex: '#02A4D3' },
        { name: 'tangaroa', hex: '#03163C' },
        { name: 'green vogue', hex: '#032B52' },
        { name: 'mosque', hex: '#036A6E' },
        { name: 'midnight moss', hex: '#041004' },
        { name: 'black pearl', hex: '#041322' },
        { name: 'blue whale', hex: '#042E4C' },
        { name: 'zuccini', hex: '#044022' },
        { name: 'teal blue', hex: '#044259' },
        { name: 'deep cove', hex: '#051040' },
        { name: 'gulf blue', hex: '#051657' },
        { name: 'venice blue', hex: '#055989' },
        { name: 'watercourse', hex: '#056F57' },
        { name: 'catalina blue', hex: '#062A78' },
        { name: 'tiber', hex: '#063537' },
        { name: 'gossamer', hex: '#069B81' },
        { name: 'niagara', hex: '#06A189' },
        { name: 'tarawera', hex: '#073A50' },
        { name: 'jaguar', hex: '#080110' },
        { name: 'black bean', hex: '#081910' },
        { name: 'deep sapphire', hex: '#082567' },
        { name: 'elf green', hex: '#088370' },
        { name: 'bright turquoise', hex: '#08E8DE' },
        { name: 'downriver', hex: '#092256' },
        { name: 'palm green', hex: '#09230F' },
        { name: 'madison', hex: '#09255D' },
        { name: 'bottle green', hex: '#093624' },
        { name: 'deep sea green', hex: '#095859' },
        { name: 'salem', hex: '#097F4B' },
        { name: 'black russian', hex: '#0A001C' },
        { name: 'dark fern', hex: '#0A480D' },
        { name: 'japanese laurel', hex: '#0A6906' },
        { name: 'atoll', hex: '#0A6F75' },
        { name: 'cod gray', hex: '#0B0B0B' },
        { name: 'marshland', hex: '#0B0F08' },
        { name: 'gordons green', hex: '#0B1107' },
        { name: 'black forest', hex: '#0B1304' },
        { name: 'san felix', hex: '#0B6207' },
        { name: 'malachite', hex: '#0BDA51' },
        { name: 'ebony', hex: '#0C0B1D' },
        { name: 'woodsmoke', hex: '#0C0D0F' },
        { name: 'racing green', hex: '#0C1911' },
        { name: 'surfie green', hex: '#0C7A79' },
        { name: 'blue chill', hex: '#0C8990' },
        { name: 'black rock', hex: '#0D0332' },
        { name: 'bunker', hex: '#0D1117' },
        { name: 'aztec', hex: '#0D1C19' },
        { name: 'bush', hex: '#0D2E1C' },
        { name: 'cinder', hex: '#0E0E18' },
        { name: 'firefly', hex: '#0E2A30' },
        { name: 'torea bay', hex: '#0F2D9E' },
        { name: 'vulcan', hex: '#10121D' },
        { name: 'green waterloo', hex: '#101405' },
        { name: 'eden', hex: '#105852' },
        { name: 'arapawa', hex: '#110C6C' },
        { name: 'ultramarine', hex: '#120A8F' },
        { name: 'elephant', hex: '#123447' },
        { name: 'jewel', hex: '#126B40' },
        { name: 'diesel', hex: '#130000' },
        { name: 'asphalt', hex: '#130A06' },
        { name: 'blue zodiac', hex: '#13264D' },
        { name: 'parsley', hex: '#134F19' },
        { name: 'nero', hex: '#140600' },
        { name: 'tory blue', hex: '#1450AA' },
        { name: 'bunting', hex: '#151F4C' },
        { name: 'denim', hex: '#1560BD' },
        { name: 'genoa', hex: '#15736B' },
        { name: 'mirage', hex: '#161928' },
        { name: 'hunter green', hex: '#161D10' },
        { name: 'big stone', hex: '#162A40' },
        { name: 'celtic', hex: '#163222' },
        { name: 'timber green', hex: '#16322C' },
        { name: 'gable green', hex: '#163531' },
        { name: 'pine tree', hex: '#171F04' },
        { name: 'chathams blue', hex: '#175579' },
        { name: 'deep forest green', hex: '#182D09' },
        { name: 'blumine', hex: '#18587A' },
        { name: 'palm leaf', hex: '#19330E' },
        { name: 'nile blue', hex: '#193751' },
        { name: 'fun blue', hex: '#1959A8' },
        { name: 'lucky point', hex: '#1A1A68' },
        { name: 'mountain meadow', hex: '#1AB385' },
        { name: 'tolopea', hex: '#1B0245' },
        { name: 'haiti', hex: '#1B1035' },
        { name: 'deep koamaru', hex: '#1B127B' },
        { name: 'acadia', hex: '#1B1404' },
        { name: 'seaweed', hex: '#1B2F11' },
        { name: 'biscay', hex: '#1B3162' },
        { name: 'matisse', hex: '#1B659D' },
        { name: 'crowshead', hex: '#1C1208' },
        { name: 'rangoon green', hex: '#1C1E13' },
        { name: 'persian blue', hex: '#1C39BB' },
        { name: 'everglade', hex: '#1C402E' },
        { name: 'elm', hex: '#1C7C7D' },
        { name: 'green pea', hex: '#1D6142' },
        { name: 'creole', hex: '#1E0F04' },
        { name: 'karaka', hex: '#1E1609' },
        { name: 'el paso', hex: '#1E1708' },
        { name: 'cello', hex: '#1E385B' },
        { name: 'te papa green', hex: '#1E433C' },
        { name: 'dodger blue', hex: '#1E90FF' },
        { name: 'eastern blue', hex: '#1E9AB0' },
        { name: 'night rider', hex: '#1F120F' },
        { name: 'java', hex: '#1FC2C2' },
        { name: 'jacksons purple', hex: '#20208D' },
        { name: 'cloud burst', hex: '#202E54' },
        { name: 'blue dianne', hex: '#204852' },
        { name: 'eternity', hex: '#211A0E' },
        { name: 'deep blue', hex: '#220878' },
        { name: 'forest green', hex: '#228B22' },
        { name: 'mallard', hex: '#233418' },
        { name: 'violet', hex: '#240A40' },
        { name: 'kilamanjaro', hex: '#240C02' },
        { name: 'log cabin', hex: '#242A1D' },
        { name: 'black olive', hex: '#242E16' },
        { name: 'green house', hex: '#24500F' },
        { name: 'graphite', hex: '#251607' },
        { name: 'cannon black', hex: '#251706' },
        { name: 'port gore', hex: '#251F4F' },
        { name: 'shark', hex: '#25272C' },
        { name: 'green kelp', hex: '#25311C' },
        { name: 'curious blue', hex: '#2596D1' },
        { name: 'paua', hex: '#260368' },
        { name: 'paris m', hex: '#26056A' },
        { name: 'wood bark', hex: '#261105' },
        { name: 'gondola', hex: '#261414' },
        { name: 'steel gray', hex: '#262335' },
        { name: 'ebony clay', hex: '#26283B' },
        { name: 'bay of many', hex: '#273A81' },
        { name: 'plantation', hex: '#27504B' },
        { name: 'eucalyptus', hex: '#278A5B' },
        { name: 'oil', hex: '#281E15' },
        { name: 'astronaut', hex: '#283A77' },
        { name: 'mariner', hex: '#286ACD' },
        { name: 'violent violet', hex: '#290C5E' },
        { name: 'bastille', hex: '#292130' },
        { name: 'zeus', hex: '#292319' },
        { name: 'charade', hex: '#292937' },
        { name: 'jelly bean', hex: '#297B9A' },
        { name: 'jungle green', hex: '#29AB87' },
        { name: 'cherry pie', hex: '#2A0359' },
        { name: 'coffee bean', hex: '#2A140E' },
        { name: 'baltic sea', hex: '#2A2630' },
        { name: 'turtle green', hex: '#2A380B' },
        { name: 'cerulean blue', hex: '#2A52BE' },
        { name: 'sepia black', hex: '#2B0202' },
        { name: 'valhalla', hex: '#2B194F' },
        { name: 'heavy metal', hex: '#2B3228' },
        { name: 'blue gem', hex: '#2C0E8C' },
        { name: 'revolver', hex: '#2C1632' },
        { name: 'bleached cedar', hex: '#2C2133' },
        { name: 'lochinvar', hex: '#2C8C84' },
        { name: 'mikado', hex: '#2D2510' },
        { name: 'outer space', hex: '#2D383A' },
        { name: 'st tropaz', hex: '#2D569B' },
        { name: 'jacaranda', hex: '#2E0329' },
        { name: 'jacko bean', hex: '#2E1905' },
        { name: 'rangitoto', hex: '#2E3222' },
        { name: 'rhino', hex: '#2E3F62' },
        { name: 'sea green', hex: '#2E8B57' },
        { name: 'scooter', hex: '#2EBFD4' },
        { name: 'onion', hex: '#2F270E' },
        { name: 'governor bay', hex: '#2F3CB3' },
        { name: 'sapphire', hex: '#2F519E' },
        { name: 'spectra', hex: '#2F5A57' },
        { name: 'casal', hex: '#2F6168' },
        { name: 'melanzane', hex: '#300529' },
        { name: 'cocoa brown', hex: '#301F1E' },
        { name: 'woodrush', hex: '#302A0F' },
        { name: 'san juan', hex: '#304B6A' },
        { name: 'turquoise', hex: '#30D5C8' },
        { name: 'eclipse', hex: '#311C17' },
        { name: 'pickled bluewood', hex: '#314459' },
        { name: 'azure', hex: '#315BA1' },
        { name: 'calypso', hex: '#31728D' },
        { name: 'paradiso', hex: '#317D82' },
        { name: 'persian indigo', hex: '#32127A' },
        { name: 'blackcurrant', hex: '#32293A' },
        { name: 'mine shaft', hex: '#323232' },
        { name: 'stromboli', hex: '#325D52' },
        { name: 'bilbao', hex: '#327C14' },
        { name: 'astral', hex: '#327DA0' },
        { name: 'christalle', hex: '#33036B' },
        { name: 'thunder', hex: '#33292F' },
        { name: 'shamrock', hex: '#33CC99' },
        { name: 'tamarind', hex: '#341515' },
        { name: 'mardi gras', hex: '#350036' },
        { name: 'valentino', hex: '#350E42' },
        { name: 'jagger', hex: '#350E57' },
        { name: 'tuna', hex: '#353542' },
        { name: 'chambray', hex: '#354E8C' },
        { name: 'martinique', hex: '#363050' },
        { name: 'tuatara', hex: '#363534' },
        { name: 'waiouru', hex: '#363C0D' },
        { name: 'ming', hex: '#36747D' },
        { name: 'la palma', hex: '#368716' },
        { name: 'chocolate', hex: '#370202' },
        { name: 'clinker', hex: '#371D09' },
        { name: 'brown tumbleweed', hex: '#37290E' },
        { name: 'birch', hex: '#373021' },
        { name: 'oracle', hex: '#377475' },
        { name: 'blue diamond', hex: '#380474' },
        { name: 'grape', hex: '#381A51' },
        { name: 'dune', hex: '#383533' },
        { name: 'oxford blue', hex: '#384555' },
        { name: 'clover', hex: '#384910' },
        { name: 'limed spruce', hex: '#394851' },
        { name: 'dell', hex: '#396413' },
        { name: 'toledo', hex: '#3A0020' },
        { name: 'sambuca', hex: '#3A2010' },
        { name: 'jacarta', hex: '#3A2A6A' },
        { name: 'william', hex: '#3A686C' },
        { name: 'killarney', hex: '#3A6A47' },
        { name: 'keppel', hex: '#3AB09E' },
        { name: 'temptress', hex: '#3B000B' },
        { name: 'aubergine', hex: '#3B0910' },
        { name: 'jon', hex: '#3B1F1F' },
        { name: 'treehouse', hex: '#3B2820' },
        { name: 'amazon', hex: '#3B7A57' },
        { name: 'boston blue', hex: '#3B91B4' },
        { name: 'windsor', hex: '#3C0878' },
        { name: 'rebel', hex: '#3C1206' },
        { name: 'meteorite', hex: '#3C1F76' },
        { name: 'dark ebony', hex: '#3C2005' },
        { name: 'camouflage', hex: '#3C3910' },
        { name: 'bright gray', hex: '#3C4151' },
        { name: 'cape cod', hex: '#3C4443' },
        { name: 'lunar green', hex: '#3C493A' },
        { name: 'bean', hex: '#3D0C02' },
        { name: 'bistre', hex: '#3D2B1F' },
        { name: 'goblin', hex: '#3D7D52' },
        { name: 'kingfisher daisy', hex: '#3E0480' },
        { name: 'cedar', hex: '#3E1C14' },
        { name: 'english walnut', hex: '#3E2B23' },
        { name: 'black marlin', hex: '#3E2C1C' },
        { name: 'ship gray', hex: '#3E3A44' },
        { name: 'pelorous', hex: '#3EABBF' },
        { name: 'bronze', hex: '#3F2109' },
        { name: 'cola', hex: '#3F2500' },
        { name: 'madras', hex: '#3F3002' },
        { name: 'minsk', hex: '#3F307F' },
        { name: 'cabbage pont', hex: '#3F4C3A' },
        { name: 'tom thumb', hex: '#3F583B' },
        { name: 'mineral green', hex: '#3F5D53' },
        { name: 'puerto rico', hex: '#3FC1AA' },
        { name: 'harlequin', hex: '#3FFF00' },
        { name: 'brown pod', hex: '#401801' },
        { name: 'cork', hex: '#40291D' },
        { name: 'masala', hex: '#403B38' },
        { name: 'thatch green', hex: '#403D19' },
        { name: 'fiord', hex: '#405169' },
        { name: 'viridian', hex: '#40826D' },
        { name: 'chateau green', hex: '#40A860' },
        { name: 'ripe plum', hex: '#410056' },
        { name: 'paco', hex: '#411F10' },
        { name: 'deep oak', hex: '#412010' },
        { name: 'merlin', hex: '#413C37' },
        { name: 'gun powder', hex: '#414257' },
        { name: 'east bay', hex: '#414C7D' },
        { name: 'royal blue', hex: '#4169E1' },
        { name: 'ocean green', hex: '#41AA78' },
        { name: 'burnt maroon', hex: '#420303' },
        { name: 'lisbon brown', hex: '#423921' },
        { name: 'faded jade', hex: '#427977' },
        { name: 'scarlet gum', hex: '#431560' },
        { name: 'iroko', hex: '#433120' },
        { name: 'armadillo', hex: '#433E37' },
        { name: 'river bed', hex: '#434C59' },
        { name: 'green leaf', hex: '#436A0D' },
        { name: 'barossa', hex: '#44012D' },
        { name: 'morocco brown', hex: '#441D00' },
        { name: 'mako', hex: '#444954' },
        { name: 'kelp', hex: '#454936' },
        { name: 'san marino', hex: '#456CAC' },
        { name: 'picton blue', hex: '#45B1E8' },
        { name: 'loulou', hex: '#460B41' },
        { name: 'crater brown', hex: '#462425' },
        { name: 'gray asparagus', hex: '#465945' },
        { name: 'steel blue', hex: '#4682B4' },
        { name: 'rustic red', hex: '#480404' },
        { name: 'bulgarian rose', hex: '#480607' },
        { name: 'clairvoyant', hex: '#480656' },
        { name: 'cocoa bean', hex: '#481C1C' },
        { name: 'woody brown', hex: '#483131' },
        { name: 'taupe', hex: '#483C32' },
        { name: 'van cleef', hex: '#49170C' },
        { name: 'brown derby', hex: '#492615' },
        { name: 'metallic bronze', hex: '#49371B' },
        { name: 'verdun green', hex: '#495400' },
        { name: 'blue bayoux', hex: '#496679' },
        { name: 'bismark', hex: '#497183' },
        { name: 'bracken', hex: '#4A2A04' },
        { name: 'deep bronze', hex: '#4A3004' },
        { name: 'mondo', hex: '#4A3C30' },
        { name: 'tundora', hex: '#4A4244' },
        { name: 'gravel', hex: '#4A444B' },
        { name: 'trout', hex: '#4A4E5A' },
        { name: 'pigment indigo', hex: '#4B0082' },
        { name: 'nandor', hex: '#4B5D52' },
        { name: 'saddle', hex: '#4C3024' },
        { name: 'abbey', hex: '#4C4F56' },
        { name: 'blackberry', hex: '#4D0135' },
        { name: 'cab sav', hex: '#4D0A18' },
        { name: 'indian tan', hex: '#4D1E01' },
        { name: 'cowboy', hex: '#4D282D' },
        { name: 'livid brown', hex: '#4D282E' },
        { name: 'rock', hex: '#4D3833' },
        { name: 'punga', hex: '#4D3D14' },
        { name: 'bronzetone', hex: '#4D400F' },
        { name: 'woodland', hex: '#4D5328' },
        { name: 'mahogany', hex: '#4E0606' },
        { name: 'bossanova', hex: '#4E2A5A' },
        { name: 'matterhorn', hex: '#4E3B41' },
        { name: 'bronze olive', hex: '#4E420C' },
        { name: 'mulled wine', hex: '#4E4562' },
        { name: 'axolotl', hex: '#4E6649' },
        { name: 'wedgewood', hex: '#4E7F9E' },
        { name: 'shakespeare', hex: '#4EABD1' },
        { name: 'honey flower', hex: '#4F1C70' },
        { name: 'daisy bush', hex: '#4F2398' },
        { name: 'indigo', hex: '#4F69C6' },
        { name: 'fern green', hex: '#4F7942' },
        { name: 'fruit salad', hex: '#4F9D5D' },
        { name: 'apple', hex: '#4FA83D' },
        { name: 'mortar', hex: '#504351' },
        { name: 'kashmir blue', hex: '#507096' },
        { name: 'cutty sark', hex: '#507672' },
        { name: 'emerald', hex: '#50C878' },
        { name: 'emperor', hex: '#514649' },
        { name: 'chalet green', hex: '#516E3D' },
        { name: 'como', hex: '#517C66' },
        { name: 'smalt blue', hex: '#51808F' },
        { name: 'castro', hex: '#52001F' },
        { name: 'maroon oak', hex: '#520C17' },
        { name: 'gigas', hex: '#523C94' },
        { name: 'voodoo', hex: '#533455' },
        { name: 'victoria', hex: '#534491' },
        { name: 'hippie green', hex: '#53824B' },
        { name: 'heath', hex: '#541012' },
        { name: 'judge gray', hex: '#544333' },
        { name: 'fuscous gray', hex: '#54534D' },
        { name: 'vida loca', hex: '#549019' },
        { name: 'cioccolato', hex: '#55280C' },
        { name: 'saratoga', hex: '#555B10' },
        { name: 'finlandia', hex: '#556D56' },
        { name: 'havelock blue', hex: '#5590D9' },
        { name: 'fountain blue', hex: '#56B4BE' },
        { name: 'spring leaves', hex: '#578363' },
        { name: 'saddle brown', hex: '#583401' },
        { name: 'scarpa flow', hex: '#585562' },
        { name: 'cactus', hex: '#587156' },
        { name: 'hippie blue', hex: '#589AAF' },
        { name: 'wine berry', hex: '#591D35' },
        { name: 'brown bramble', hex: '#592804' },
        { name: 'congo brown', hex: '#593737' },
        { name: 'millbrook', hex: '#594433' },
        { name: 'waikawa gray', hex: '#5A6E9C' },
        { name: 'horizon', hex: '#5A87A0' },
        { name: 'jambalaya', hex: '#5B3013' },
        { name: 'bordeaux', hex: '#5C0120' },
        { name: 'mulberry wood', hex: '#5C0536' },
        { name: 'carnaby tan', hex: '#5C2E01' },
        { name: 'comet', hex: '#5C5D75' },
        { name: 'redwood', hex: '#5D1E0F' },
        { name: 'don juan', hex: '#5D4C51' },
        { name: 'chicago', hex: '#5D5C58' },
        { name: 'verdigris', hex: '#5D5E37' },
        { name: 'dingley', hex: '#5D7747' },
        { name: 'breaker bay', hex: '#5DA19F' },
        { name: 'kabul', hex: '#5E483E' },
        { name: 'hemlock', hex: '#5E5D3B' },
        { name: 'irish coffee', hex: '#5F3D26' },
        { name: 'mid gray', hex: '#5F5F6E' },
        { name: 'shuttle gray', hex: '#5F6672' },
        { name: 'aqua forest', hex: '#5FA777' },
        { name: 'tradewind', hex: '#5FB3AC' },
        { name: 'horses neck', hex: '#604913' },
        { name: 'smoky', hex: '#605B73' },
        { name: 'corduroy', hex: '#606E68' },
        { name: 'danube', hex: '#6093D1' },
        { name: 'espresso', hex: '#612718' },
        { name: 'eggplant', hex: '#614051' },
        { name: 'costa del sol', hex: '#615D30' },
        { name: 'glade green', hex: '#61845F' },
        { name: 'buccaneer', hex: '#622F30' },
        { name: 'quincy', hex: '#623F2D' },
        { name: 'butterfly bush', hex: '#624E9A' },
        { name: 'west coast', hex: '#625119' },
        { name: 'finch', hex: '#626649' },
        { name: 'patina', hex: '#639A8F' },
        { name: 'fern', hex: '#63B76C' },
        { name: 'blue violet', hex: '#6456B7' },
        { name: 'dolphin', hex: '#646077' },
        { name: 'storm dust', hex: '#646463' },
        { name: 'siam', hex: '#646A54' },
        { name: 'nevada', hex: '#646E75' },
        { name: 'cornflower blue', hex: '#6495ED' },
        { name: 'viking', hex: '#64CCDB' },
        { name: 'rosewood', hex: '#65000B' },
        { name: 'cherrywood', hex: '#651A14' },
        { name: 'purple heart', hex: '#652DC1' },
        { name: 'fern frond', hex: '#657220' },
        { name: 'willow grove', hex: '#65745D' },
        { name: 'hoki', hex: '#65869F' },
        { name: 'pompadour', hex: '#660045' },
        { name: 'purple', hex: '#660099' },
        { name: 'tyrian purple', hex: '#66023C' },
        { name: 'dark tan', hex: '#661010' },
        { name: 'silver tree', hex: '#66B58F' },
        { name: 'bright green', hex: '#66FF00' },
        { name: "screamin' green", hex: '#66FF66' },
        { name: 'black rose', hex: '#67032D' },
        { name: 'scampi', hex: '#675FA6' },
        { name: 'ironside gray', hex: '#676662' },
        { name: 'viridian green', hex: '#678975' },
        { name: 'christi', hex: '#67A712' },
        { name: 'nutmeg wood finish', hex: '#683600' },
        { name: 'zambezi', hex: '#685558' },
        { name: 'salt box', hex: '#685E6E' },
        { name: 'tawny port', hex: '#692545' },
        { name: 'finn', hex: '#692D54' },
        { name: 'scorpion', hex: '#695F62' },
        { name: 'lynch', hex: '#697E9A' },
        { name: 'spice', hex: '#6A442E' },
        { name: 'himalaya', hex: '#6A5D1B' },
        { name: 'soya bean', hex: '#6A6051' },
        { name: 'hairy heath', hex: '#6B2A14' },
        { name: 'royal purple', hex: '#6B3FA0' },
        { name: 'shingle fawn', hex: '#6B4E31' },
        { name: 'dorado', hex: '#6B5755' },
        { name: 'bermuda gray', hex: '#6B8BA2' },
        { name: 'olive drab', hex: '#6B8E23' },
        { name: 'eminence', hex: '#6C3082' },
        { name: 'turquoise blue', hex: '#6CDAE7' },
        { name: 'lonestar', hex: '#6D0101' },
        { name: 'pine cone', hex: '#6D5E54' },
        { name: 'dove gray', hex: '#6D6C6C' },
        { name: 'juniper', hex: '#6D9292' },
        { name: 'gothic', hex: '#6D92A1' },
        { name: 'red oxide', hex: '#6E0902' },
        { name: 'moccaccino', hex: '#6E1D14' },
        { name: 'pickled bean', hex: '#6E4826' },
        { name: 'dallas', hex: '#6E4B26' },
        { name: 'kokoda', hex: '#6E6D57' },
        { name: 'pale sky', hex: '#6E7783' },
        { name: 'cafe royale', hex: '#6F440C' },
        { name: 'flint', hex: '#6F6A61' },
        { name: 'highland', hex: '#6F8E63' },
        { name: 'limeade', hex: '#6F9D02' },
        { name: 'downy', hex: '#6FD0C5' },
        { name: 'persian plum', hex: '#701C1C' },
        { name: 'sepia', hex: '#704214' },
        { name: 'antique bronze', hex: '#704A07' },
        { name: 'ferra', hex: '#704F50' },
        { name: 'coffee', hex: '#706555' },
        { name: 'slate gray', hex: '#708090' },
        { name: 'cedar wood finish', hex: '#711A00' },
        { name: 'metallic copper', hex: '#71291D' },
        { name: 'affair', hex: '#714693' },
        { name: 'studio', hex: '#714AB2' },
        { name: 'tobacco brown', hex: '#715D47' },
        { name: 'yellow metal', hex: '#716338' },
        { name: 'peat', hex: '#716B56' },
        { name: 'olivetone', hex: '#716E10' },
        { name: 'storm gray', hex: '#717486' },
        { name: 'sirocco', hex: '#718080' },
        { name: 'aquamarine blue', hex: '#71D9E2' },
        { name: 'venetian red', hex: '#72010F' },
        { name: 'old copper', hex: '#724A2F' },
        { name: 'go ben', hex: '#726D4E' },
        { name: 'raven', hex: '#727B89' },
        { name: 'seance', hex: '#731E8F' },
        { name: 'raw umber', hex: '#734A12' },
        { name: 'kimberly', hex: '#736C9F' },
        { name: 'crocodile', hex: '#736D58' },
        { name: 'crete', hex: '#737829' },
        { name: 'xanadu', hex: '#738678' },
        { name: 'spicy mustard', hex: '#74640D' },
        { name: 'limed ash', hex: '#747D63' },
        { name: 'rolling stone', hex: '#747D83' },
        { name: 'blue smoke', hex: '#748881' },
        { name: 'laurel', hex: '#749378' },
        { name: 'mantis', hex: '#74C365' },
        { name: 'russett', hex: '#755A57' },
        { name: 'deluge', hex: '#7563A8' },
        { name: 'cosmic', hex: '#76395D' },
        { name: 'blue marguerite', hex: '#7666C6' },
        { name: 'lima', hex: '#76BD17' },
        { name: 'sky blue', hex: '#76D7EA' },
        { name: 'dark burgundy', hex: '#770F05' },
        { name: 'crown of thorns', hex: '#771F1F' },
        { name: 'walnut', hex: '#773F1A' },
        { name: 'pablo', hex: '#776F61' },
        { name: 'pacifika', hex: '#778120' },
        { name: 'oxley', hex: '#779E86' },
        { name: 'pastel green', hex: '#77DD77' },
        { name: 'japanese maple', hex: '#780109' },
        { name: 'mocha', hex: '#782D19' },
        { name: 'peanut', hex: '#782F16' },
        { name: 'camouflage green', hex: '#78866B' },
        { name: 'wasabi', hex: '#788A25' },
        { name: 'ship cove', hex: '#788BBA' },
        { name: 'sea nymph', hex: '#78A39C' },
        { name: 'roman coffee', hex: '#795D4C' },
        { name: 'old lavender', hex: '#796878' },
        { name: 'rum', hex: '#796989' },
        { name: 'fedora', hex: '#796A78' },
        { name: 'sandstone', hex: '#796D62' },
        { name: 'spray', hex: '#79DEEC' },
        { name: 'siren', hex: '#7A013A' },
        { name: 'fuchsia blue', hex: '#7A58C1' },
        { name: 'boulder', hex: '#7A7A7A' },
        { name: 'wild blue yonder', hex: '#7A89B8' },
        { name: 'de york', hex: '#7AC488' },
        { name: 'red beech', hex: '#7B3801' },
        { name: 'cinnamon', hex: '#7B3F00' },
        { name: 'yukon gold', hex: '#7B6608' },
        { name: 'tapa', hex: '#7B7874' },
        { name: 'waterloo', hex: '#7B7C94' },
        { name: 'flax smoke', hex: '#7B8265' },
        { name: 'amulet', hex: '#7B9F80' },
        { name: 'asparagus', hex: '#7BA05B' },
        { name: 'kenyan copper', hex: '#7C1C05' },
        { name: 'pesto', hex: '#7C7631' },
        { name: 'topaz', hex: '#7C778A' },
        { name: 'concord', hex: '#7C7B7A' },
        { name: 'jumbo', hex: '#7C7B82' },
        { name: 'trendy green', hex: '#7C881A' },
        { name: 'gumbo', hex: '#7CA1A6' },
        { name: 'acapulco', hex: '#7CB0A1' },
        { name: 'neptune', hex: '#7CB7BB' },
        { name: 'pueblo', hex: '#7D2C14' },
        { name: 'bay leaf', hex: '#7DA98D' },
        { name: 'malibu', hex: '#7DC8F7' },
        { name: 'bermuda', hex: '#7DD8C6' },
        { name: 'copper canyon', hex: '#7E3A15' },
        { name: 'claret', hex: '#7F1734' },
        { name: 'peru tan', hex: '#7F3A02' },
        { name: 'falcon', hex: '#7F626D' },
        { name: 'mobster', hex: '#7F7589' },
        { name: 'moody blue', hex: '#7F76D3' },
        { name: 'chartreuse', hex: '#7FFF00' },
        { name: 'aquamarine', hex: '#7FFFD4' },
        { name: 'maroon', hex: '#800000' },
        { name: 'rose bud cherry', hex: '#800B47' },
        { name: 'falu red', hex: '#801818' },
        { name: 'red robin', hex: '#80341F' },
        { name: 'vivid violet', hex: '#803790' },
        { name: 'russet', hex: '#80461B' },
        { name: 'friar gray', hex: '#807E79' },
        { name: 'olive', hex: '#808000' },
        { name: 'gray', hex: '#808080' },
        { name: 'gulf stream', hex: '#80B3AE' },
        { name: 'glacier', hex: '#80B3C4' },
        { name: 'seagull', hex: '#80CCEA' },
        { name: 'nutmeg', hex: '#81422C' },
        { name: 'spicy pink', hex: '#816E71' },
        { name: 'empress', hex: '#817377' },
        { name: 'spanish green', hex: '#819885' },
        { name: 'sand dune', hex: '#826F65' },
        { name: 'gunsmoke', hex: '#828685' },
        { name: 'battleship gray', hex: '#828F72' },
        { name: 'merlot', hex: '#831923' },
        { name: 'shadow', hex: '#837050' },
        { name: 'chelsea cucumber', hex: '#83AA5D' },
        { name: 'monte carlo', hex: '#83D0C6' },
        { name: 'plum', hex: '#843179' },
        { name: 'granny smith', hex: '#84A0A0' },
        { name: 'chetwode blue', hex: '#8581D9' },
        { name: 'bandicoot', hex: '#858470' },
        { name: 'bali hai', hex: '#859FAF' },
        { name: 'half baked', hex: '#85C4CC' },
        { name: 'red devil', hex: '#860111' },
        { name: 'lotus', hex: '#863C3C' },
        { name: 'ironstone', hex: '#86483C' },
        { name: 'bull shot', hex: '#864D1E' },
        { name: 'rusty nail', hex: '#86560A' },
        { name: 'bitter', hex: '#868974' },
        { name: 'regent gray', hex: '#86949F' },
        { name: 'disco', hex: '#871550' },
        { name: 'americano', hex: '#87756E' },
        { name: 'hurricane', hex: '#877C7B' },
        { name: 'oslo gray', hex: '#878D91' },
        { name: 'sushi', hex: '#87AB39' },
        { name: 'spicy mix', hex: '#885342' },
        { name: 'kumera', hex: '#886221' },
        { name: 'suva gray', hex: '#888387' },
        { name: 'avocado', hex: '#888D65' },
        { name: 'camelot', hex: '#893456' },
        { name: 'solid pink', hex: '#893843' },
        { name: 'cannon pink', hex: '#894367' },
        { name: 'makara', hex: '#897D6D' },
        { name: 'burnt umber', hex: '#8A3324' },
        { name: 'true v', hex: '#8A73D6' },
        { name: 'clay creek', hex: '#8A8360' },
        { name: 'monsoon', hex: '#8A8389' },
        { name: 'stack', hex: '#8A8F8A' },
        { name: 'jordy blue', hex: '#8AB9F1' },
        { name: 'electric violet', hex: '#8B00FF' },
        { name: 'monarch', hex: '#8B0723' },
        { name: 'corn harvest', hex: '#8B6B0B' },
        { name: 'olive haze', hex: '#8B8470' },
        { name: 'schooner', hex: '#8B847E' },
        { name: 'natural gray', hex: '#8B8680' },
        { name: 'mantle', hex: '#8B9C90' },
        { name: 'portage', hex: '#8B9FEE' },
        { name: 'envy', hex: '#8BA690' },
        { name: 'cascade', hex: '#8BA9A5' },
        { name: 'riptide', hex: '#8BE6D8' },
        { name: 'cardinal pink', hex: '#8C055E' },
        { name: 'mule fawn', hex: '#8C472F' },
        { name: 'potters clay', hex: '#8C5738' },
        { name: 'trendy pink', hex: '#8C6495' },
        { name: 'paprika', hex: '#8D0226' },
        { name: 'sanguine brown', hex: '#8D3D38' },
        { name: 'tosca', hex: '#8D3F3F' },
        { name: 'cement', hex: '#8D7662' },
        { name: 'granite green', hex: '#8D8974' },
        { name: 'manatee', hex: '#8D90A1' },
        { name: 'polo blue', hex: '#8DA8CC' },
        { name: 'red berry', hex: '#8E0000' },
        { name: 'rope', hex: '#8E4D1E' },
        { name: 'opium', hex: '#8E6F70' },
        { name: 'domino', hex: '#8E775E' },
        { name: 'mamba', hex: '#8E8190' },
        { name: 'nepal', hex: '#8EABC1' },
        { name: 'pohutukawa', hex: '#8F021C' },
        { name: 'el salva', hex: '#8F3E33' },
        { name: 'korma', hex: '#8F4B0E' },
        { name: 'squirrel', hex: '#8F8176' },
        { name: 'vista blue', hex: '#8FD6B4' },
        { name: 'burgundy', hex: '#900020' },
        { name: 'old brick', hex: '#901E1E' },
        { name: 'hemp', hex: '#907874' },
        { name: 'almond frost', hex: '#907B71' },
        { name: 'sycamore', hex: '#908D39' },
        { name: 'sangria', hex: '#92000A' },
        { name: 'cumin', hex: '#924321' },
        { name: 'beaver', hex: '#926F5B' },
        { name: 'stonewall', hex: '#928573' },
        { name: 'venus', hex: '#928590' },
        { name: 'medium purple', hex: '#9370DB' },
        { name: 'cornflower', hex: '#93CCEA' },
        { name: 'algae green', hex: '#93DFB8' },
        { name: 'copper rust', hex: '#944747' },
        { name: 'arrowtown', hex: '#948771' },
        { name: 'scarlett', hex: '#950015' },
        { name: 'strikemaster', hex: '#956387' },
        { name: 'mountain mist', hex: '#959396' },
        { name: 'carmine', hex: '#960018' },
        { name: 'brown', hex: '#964B00' },
        { name: 'leather', hex: '#967059' },
        { name: "purple mountain's majesty", hex: '#9678B6' },
        { name: 'lavender purple', hex: '#967BB6' },
        { name: 'pewter', hex: '#96A8A1' },
        { name: 'summer green', hex: '#96BBAB' },
        { name: 'au chico', hex: '#97605D' },
        { name: 'wisteria', hex: '#9771B5' },
        { name: 'atlantis', hex: '#97CD2D' },
        { name: 'vin rouge', hex: '#983D61' },
        { name: 'lilac bush', hex: '#9874D3' },
        { name: 'bazaar', hex: '#98777B' },
        { name: 'hacienda', hex: '#98811B' },
        { name: 'pale oyster', hex: '#988D77' },
        { name: 'mint green', hex: '#98FF98' },
        { name: 'fresh eggplant', hex: '#990066' },
        { name: 'violet eggplant', hex: '#991199' },
        { name: 'tamarillo', hex: '#991613' },
        { name: 'totem pole', hex: '#991B07' },
        { name: 'copper rose', hex: '#996666' },
        { name: 'amethyst', hex: '#9966CC' },
        { name: 'mountbatten pink', hex: '#997A8D' },
        { name: 'blue bell', hex: '#9999CC' },
        { name: 'prairie sand', hex: '#9A3820' },
        { name: 'toast', hex: '#9A6E61' },
        { name: 'gurkha', hex: '#9A9577' },
        { name: 'olivine', hex: '#9AB973' },
        { name: 'shadow green', hex: '#9AC2B8' },
        { name: 'oregon', hex: '#9B4703' },
        { name: 'lemon grass', hex: '#9B9E8F' },
        { name: 'stiletto', hex: '#9C3336' },
        { name: 'hawaiian tan', hex: '#9D5616' },
        { name: 'gull gray', hex: '#9DACB7' },
        { name: 'pistachio', hex: '#9DC209' },
        { name: 'granny smith apple', hex: '#9DE093' },
        { name: 'anakiwa', hex: '#9DE5FF' },
        { name: 'chelsea gem', hex: '#9E5302' },
        { name: 'sepia skin', hex: '#9E5B40' },
        { name: 'sage', hex: '#9EA587' },
        { name: 'citron', hex: '#9EA91F' },
        { name: 'rock blue', hex: '#9EB1CD' },
        { name: 'morning glory', hex: '#9EDEE0' },
        { name: 'cognac', hex: '#9F381D' },
        { name: 'reef gold', hex: '#9F821C' },
        { name: 'star dust', hex: '#9F9F9C' },
        { name: 'santas gray', hex: '#9FA0B1' },
        { name: 'sinbad', hex: '#9FD7D3' },
        { name: 'feijoa', hex: '#9FDD8C' },
        { name: 'tabasco', hex: '#A02712' },
        { name: 'buttered rum', hex: '#A1750D' },
        { name: 'hit gray', hex: '#A1ADB5' },
        { name: 'citrus', hex: '#A1C50A' },
        { name: 'aqua island', hex: '#A1DAD7' },
        { name: 'water leaf', hex: '#A1E9DE' },
        { name: 'flirt', hex: '#A2006D' },
        { name: 'rouge', hex: '#A23B6C' },
        { name: 'cape palliser', hex: '#A26645' },
        { name: 'gray chateau', hex: '#A2AAB3' },
        { name: 'edward', hex: '#A2AEAB' },
        { name: 'pharlap', hex: '#A3807B' },
        { name: 'amethyst smoke', hex: '#A397B4' },
        { name: 'blizzard blue', hex: '#A3E3ED' },
        { name: 'delta', hex: '#A4A49D' },
        { name: 'wistful', hex: '#A4A6D3' },
        { name: 'green smoke', hex: '#A4AF6E' },
        { name: 'jazzberry jam', hex: '#A50B5E' },
        { name: 'zorba', hex: '#A59B91' },
        { name: 'bahia', hex: '#A5CB0C' },
        { name: 'roof terracotta', hex: '#A62F20' },
        { name: 'paarl', hex: '#A65529' },
        { name: 'barley corn', hex: '#A68B5B' },
        { name: 'donkey brown', hex: '#A69279' },
        { name: 'dawn', hex: '#A6A29A' },
        { name: 'mexican red', hex: '#A72525' },
        { name: 'luxor gold', hex: '#A7882C' },
        { name: 'rich gold', hex: '#A85307' },
        { name: 'reno sand', hex: '#A86515' },
        { name: 'coral tree', hex: '#A86B6B' },
        { name: 'dusty gray', hex: '#A8989B' },
        { name: 'dull lavender', hex: '#A899E6' },
        { name: 'tallow', hex: '#A8A589' },
        { name: 'bud', hex: '#A8AE9C' },
        { name: 'locust', hex: '#A8AF8E' },
        { name: 'norway', hex: '#A8BD9F' },
        { name: 'chinook', hex: '#A8E3BD' },
        { name: 'gray olive', hex: '#A9A491' },
        { name: 'aluminium', hex: '#A9ACB6' },
        { name: 'cadet blue', hex: '#A9B2C3' },
        { name: 'schist', hex: '#A9B497' },
        { name: 'tower gray', hex: '#A9BDBF' },
        { name: 'perano', hex: '#A9BEF2' },
        { name: 'opal', hex: '#A9C6C2' },
        { name: 'night shadz', hex: '#AA375A' },
        { name: 'fire', hex: '#AA4203' },
        { name: 'muesli', hex: '#AA8B5B' },
        { name: 'sandal', hex: '#AA8D6F' },
        { name: 'shady lady', hex: '#AAA5A9' },
        { name: 'logan', hex: '#AAA9CD' },
        { name: 'spun pearl', hex: '#AAABB7' },
        { name: 'regent st blue', hex: '#AAD6E6' },
        { name: 'magic mint', hex: '#AAF0D1' },
        { name: 'lipstick', hex: '#AB0563' },
        { name: 'royal heath', hex: '#AB3472' },
        { name: 'sandrift', hex: '#AB917A' },
        { name: 'cold purple', hex: '#ABA0D9' },
        { name: 'bronco', hex: '#ABA196' },
        { name: 'limed oak', hex: '#AC8A56' },
        { name: 'east side', hex: '#AC91CE' },
        { name: 'lemon ginger', hex: '#AC9E22' },
        { name: 'napa', hex: '#ACA494' },
        { name: 'hillary', hex: '#ACA586' },
        { name: 'cloudy', hex: '#ACA59F' },
        { name: 'silver chalice', hex: '#ACACAC' },
        { name: 'swamp green', hex: '#ACB78E' },
        { name: 'spring rain', hex: '#ACCBB1' },
        { name: 'conifer', hex: '#ACDD4D' },
        { name: 'celadon', hex: '#ACE1AF' },
        { name: 'mandalay', hex: '#AD781B' },
        { name: 'casper', hex: '#ADBED1' },
        { name: 'moss green', hex: '#ADDFAD' },
        { name: 'padua', hex: '#ADE6C4' },
        { name: 'green yellow', hex: '#ADFF2F' },
        { name: 'hippie pink', hex: '#AE4560' },
        { name: 'desert', hex: '#AE6020' },
        { name: 'bouquet', hex: '#AE809E' },
        { name: 'medium carmine', hex: '#AF4035' },
        { name: 'apple blossom', hex: '#AF4D43' },
        { name: 'brown rust', hex: '#AF593E' },
        { name: 'driftwood', hex: '#AF8751' },
        { name: 'alpine', hex: '#AF8F2C' },
        { name: 'lucky', hex: '#AF9F1C' },
        { name: 'martini', hex: '#AFA09E' },
        { name: 'bombay', hex: '#AFB1B8' },
        { name: 'pigeon post', hex: '#AFBDD9' },
        { name: 'cadillac', hex: '#B04C6A' },
        { name: 'matrix', hex: '#B05D54' },
        { name: 'tapestry', hex: '#B05E81' },
        { name: 'mai tai', hex: '#B06608' },
        { name: 'del rio', hex: '#B09A95' },
        { name: 'powder blue', hex: '#B0E0E6' },
        { name: 'inch worm', hex: '#B0E313' },
        { name: 'bright red', hex: '#B10000' },
        { name: 'vesuvius', hex: '#B14A0B' },
        { name: 'pumpkin skin', hex: '#B1610B' },
        { name: 'santa fe', hex: '#B16D52' },
        { name: 'teak', hex: '#B19461' },
        { name: 'fringy flower', hex: '#B1E2C1' },
        { name: 'ice cold', hex: '#B1F4E7' },
        { name: 'shiraz', hex: '#B20931' },
        { name: 'biloba flower', hex: '#B2A1EA' },
        { name: 'tall poppy', hex: '#B32D29' },
        { name: 'fiery orange', hex: '#B35213' },
        { name: 'hot toddy', hex: '#B38007' },
        { name: 'taupe gray', hex: '#B3AF95' },
        { name: 'la rioja', hex: '#B3C110' },
        { name: 'well read', hex: '#B43332' },
        { name: 'blush', hex: '#B44668' },
        { name: 'jungle mist', hex: '#B4CFD3' },
        { name: 'turkish rose', hex: '#B57281' },
        { name: 'lavender', hex: '#B57EDC' },
        { name: 'mongoose', hex: '#B5A27F' },
        { name: 'olive green', hex: '#B5B35C' },
        { name: 'jet stream', hex: '#B5D2CE' },
        { name: 'cruise', hex: '#B5ECDF' },
        { name: 'hibiscus', hex: '#B6316C' },
        { name: 'thatch', hex: '#B69D98' },
        { name: 'heathered gray', hex: '#B6B095' },
        { name: 'eagle', hex: '#B6BAA4' },
        { name: 'spindle', hex: '#B6D1EA' },
        { name: 'gum leaf', hex: '#B6D3BF' },
        { name: 'rust', hex: '#B7410E' },
        { name: 'muddy waters', hex: '#B78E5C' },
        { name: 'sahara', hex: '#B7A214' },
        { name: 'husk', hex: '#B7A458' },
        { name: 'nobel', hex: '#B7B1B1' },
        { name: 'heather', hex: '#B7C3D0' },
        { name: 'madang', hex: '#B7F0BE' },
        { name: 'milano red', hex: '#B81104' },
        { name: 'copper', hex: '#B87333' },
        { name: 'gimblet', hex: '#B8B56A' },
        { name: 'green spring', hex: '#B8C1B1' },
        { name: 'celery', hex: '#B8C25D' },
        { name: 'sail', hex: '#B8E0F9' },
        { name: 'chestnut', hex: '#B94E48' },
        { name: 'crail', hex: '#B95140' },
        { name: 'marigold', hex: '#B98D28' },
        { name: 'wild willow', hex: '#B9C46A' },
        { name: 'rainee', hex: '#B9C8AC' },
        { name: 'guardsman red', hex: '#BA0101' },
        { name: 'rock spray', hex: '#BA450C' },
        { name: 'bourbon', hex: '#BA6F1E' },
        { name: 'pirate gold', hex: '#BA7F03' },
        { name: 'nomad', hex: '#BAB1A2' },
        { name: 'submarine', hex: '#BAC7C9' },
        { name: 'charlotte', hex: '#BAEEF9' },
        { name: 'medium red violet', hex: '#BB3385' },
        { name: 'brandy rose', hex: '#BB8983' },
        { name: 'rio grande', hex: '#BBD009' },
        { name: 'surf', hex: '#BBD7C1' },
        { name: 'powder ash', hex: '#BCC9C2' },
        { name: 'tuscany', hex: '#BD5E2E' },
        { name: 'quicksand', hex: '#BD978E' },
        { name: 'silk', hex: '#BDB1A8' },
        { name: 'malta', hex: '#BDB2A1' },
        { name: 'chatelle', hex: '#BDB3C7' },
        { name: 'lavender gray', hex: '#BDBBD7' },
        { name: 'french gray', hex: '#BDBDC6' },
        { name: 'clay ash', hex: '#BDC8B3' },
        { name: 'loblolly', hex: '#BDC9CE' },
        { name: 'french pass', hex: '#BDEDFD' },
        { name: 'london hue', hex: '#BEA6C3' },
        { name: 'pink swan', hex: '#BEB5B7' },
        { name: 'fuego', hex: '#BEDE0D' },
        { name: 'rose of sharon', hex: '#BF5500' },
        { name: 'tide', hex: '#BFB8B0' },
        { name: 'blue haze', hex: '#BFBED8' },
        { name: 'silver sand', hex: '#BFC1C2' },
        { name: 'key lime pie', hex: '#BFC921' },
        { name: 'ziggurat', hex: '#BFDBE2' },
        { name: 'lime', hex: '#BFFF00' },
        { name: 'thunderbird', hex: '#C02B18' },
        { name: 'mojo', hex: '#C04737' },
        { name: 'old rose', hex: '#C08081' },
        { name: 'silver', hex: '#C0C0C0' },
        { name: 'pale leaf', hex: '#C0D3B9' },
        { name: 'pixie green', hex: '#C0D8B6' },
        { name: 'tia maria', hex: '#C1440E' },
        { name: 'fuchsia pink', hex: '#C154C1' },
        { name: 'buddha gold', hex: '#C1A004' },
        { name: 'bison hide', hex: '#C1B7A4' },
        { name: 'tea', hex: '#C1BAB0' },
        { name: 'gray suit', hex: '#C1BECD' },
        { name: 'sprout', hex: '#C1D7B0' },
        { name: 'sulu', hex: '#C1F07C' },
        { name: 'indochine', hex: '#C26B03' },
        { name: 'twine', hex: '#C2955D' },
        { name: 'cotton seed', hex: '#C2BDB6' },
        { name: 'pumice', hex: '#C2CAC4' },
        { name: 'jagged ice', hex: '#C2E8E5' },
        { name: 'maroon flush', hex: '#C32148' },
        { name: 'indian khaki', hex: '#C3B091' },
        { name: 'pale slate', hex: '#C3BFC1' },
        { name: 'gray nickel', hex: '#C3C3BD' },
        { name: 'periwinkle gray', hex: '#C3CDE6' },
        { name: 'tiara', hex: '#C3D1D1' },
        { name: 'tropical blue', hex: '#C3DDF9' },
        { name: 'cardinal', hex: '#C41E3A' },
        { name: 'fuzzy wuzzy brown', hex: '#C45655' },
        { name: 'orange roughy', hex: '#C45719' },
        { name: 'mist gray', hex: '#C4C4BC' },
        { name: 'coriander', hex: '#C4D0B0' },
        { name: 'mint tulip', hex: '#C4F4EB' },
        { name: 'mulberry', hex: '#C54B8C' },
        { name: 'nugget', hex: '#C59922' },
        { name: 'tussock', hex: '#C5994B' },
        { name: 'sea mist', hex: '#C5DBCA' },
        { name: 'yellow green', hex: '#C5E17A' },
        { name: 'brick red', hex: '#C62D42' },
        { name: 'contessa', hex: '#C6726B' },
        { name: 'oriental pink', hex: '#C69191' },
        { name: 'roti', hex: '#C6A84B' },
        { name: 'ash', hex: '#C6C3B5' },
        { name: 'kangaroo', hex: '#C6C8BD' },
        { name: 'las palmas', hex: '#C6E610' },
        { name: 'monza', hex: '#C7031E' },
        { name: 'red violet', hex: '#C71585' },
        { name: 'coral reef', hex: '#C7BCA2' },
        { name: 'melrose', hex: '#C7C1FF' },
        { name: 'cloud', hex: '#C7C4BF' },
        { name: 'ghost', hex: '#C7C9D5' },
        { name: 'pine glade', hex: '#C7CD90' },
        { name: 'botticelli', hex: '#C7DDE5' },
        { name: 'antique brass', hex: '#C88A65' },
        { name: 'lilac', hex: '#C8A2C8' },
        { name: 'hokey pokey', hex: '#C8A528' },
        { name: 'lily', hex: '#C8AABF' },
        { name: 'laser', hex: '#C8B568' },
        { name: 'edgewater', hex: '#C8E3D7' },
        { name: 'piper', hex: '#C96323' },
        { name: 'pizza', hex: '#C99415' },
        { name: 'light wisteria', hex: '#C9A0DC' },
        { name: 'rodeo dust', hex: '#C9B29B' },
        { name: 'sundance', hex: '#C9B35B' },
        { name: 'earls green', hex: '#C9B93B' },
        { name: 'silver rust', hex: '#C9C0BB' },
        { name: 'conch', hex: '#C9D9D2' },
        { name: 'reef', hex: '#C9FFA2' },
        { name: 'aero blue', hex: '#C9FFE5' },
        { name: 'flush mahogany', hex: '#CA3435' },
        { name: 'turmeric', hex: '#CABB48' },
        { name: 'paris white', hex: '#CADCD4' },
        { name: 'bitter lemon', hex: '#CAE00D' },
        { name: 'skeptic', hex: '#CAE6DA' },
        { name: 'viola', hex: '#CB8FA9' },
        { name: 'foggy gray', hex: '#CBCAB6' },
        { name: 'green mist', hex: '#CBD3B0' },
        { name: 'nebula', hex: '#CBDBD6' },
        { name: 'persian red', hex: '#CC3333' },
        { name: 'burnt orange', hex: '#CC5500' },
        { name: 'ochre', hex: '#CC7722' },
        { name: 'puce', hex: '#CC8899' },
        { name: 'thistle green', hex: '#CCCAA8' },
        { name: 'periwinkle', hex: '#CCCCFF' },
        { name: 'electric lime', hex: '#CCFF00' },
        { name: 'tenn', hex: '#CD5700' },
        { name: 'chestnut rose', hex: '#CD5C5C' },
        { name: 'brandy punch', hex: '#CD8429' },
        { name: 'onahau', hex: '#CDF4FF' },
        { name: 'sorrell brown', hex: '#CEB98F' },
        { name: 'cold turkey', hex: '#CEBABA' },
        { name: 'yuma', hex: '#CEC291' },
        { name: 'chino', hex: '#CEC7A7' },
        { name: 'eunry', hex: '#CFA39D' },
        { name: 'old gold', hex: '#CFB53B' },
        { name: 'tasman', hex: '#CFDCCF' },
        { name: 'surf crest', hex: '#CFE5D2' },
        { name: 'humming bird', hex: '#CFF9F3' },
        { name: 'scandal', hex: '#CFFAF4' },
        { name: 'red stage', hex: '#D05F04' },
        { name: 'hopbush', hex: '#D06DA1' },
        { name: 'meteor', hex: '#D07D12' },
        { name: 'perfume', hex: '#D0BEF8' },
        { name: 'prelude', hex: '#D0C0E5' },
        { name: 'tea green', hex: '#D0F0C0' },
        { name: 'geebung', hex: '#D18F1B' },
        { name: 'vanilla', hex: '#D1BEA8' },
        { name: 'soft amber', hex: '#D1C6B4' },
        { name: 'celeste', hex: '#D1D2CA' },
        { name: 'mischka', hex: '#D1D2DD' },
        { name: 'pear', hex: '#D1E231' },
        { name: 'hot cinnamon', hex: '#D2691E' },
        { name: 'raw sienna', hex: '#D27D46' },
        { name: 'careys pink', hex: '#D29EAA' },
        { name: 'tan', hex: '#D2B48C' },
        { name: 'deco', hex: '#D2DA97' },
        { name: 'blue romance', hex: '#D2F6DE' },
        { name: 'gossip', hex: '#D2F8B0' },
        { name: 'sisal', hex: '#D3CBBA' },
        { name: 'swirl', hex: '#D3CDC5' },
        { name: 'charm', hex: '#D47494' },
        { name: 'clam shell', hex: '#D4B6AF' },
        { name: 'straw', hex: '#D4BF8D' },
        { name: 'akaroa', hex: '#D4C4A8' },
        { name: 'bird flower', hex: '#D4CD16' },
        { name: 'iron', hex: '#D4D7D9' },
        { name: 'geyser', hex: '#D4DFE2' },
        { name: 'hawkes blue', hex: '#D4E2FC' },
        { name: 'grenadier', hex: '#D54600' },
        { name: 'can can', hex: '#D591A4' },
        { name: 'whiskey', hex: '#D59A6F' },
        { name: 'winter hazel', hex: '#D5D195' },
        { name: 'granny apple', hex: '#D5F6E3' },
        { name: 'my pink', hex: '#D69188' },
        { name: 'tacha', hex: '#D6C562' },
        { name: 'moon raker', hex: '#D6CEF6' },
        { name: 'quill gray', hex: '#D6D6D1' },
        { name: 'snowy mint', hex: '#D6FFDB' },
        { name: 'new york pink', hex: '#D7837F' },
        { name: 'pavlova', hex: '#D7C498' },
        { name: 'fog', hex: '#D7D0FF' },
        { name: 'valencia', hex: '#D84437' },
        { name: 'japonica', hex: '#D87C63' },
        { name: 'thistle', hex: '#D8BFD8' },
        { name: 'maverick', hex: '#D8C2D5' },
        { name: 'foam', hex: '#D8FCFA' },
        { name: 'cabaret', hex: '#D94972' },
        { name: 'burning sand', hex: '#D99376' },
        { name: 'cameo', hex: '#D9B99B' },
        { name: 'timberwolf', hex: '#D9D6CF' },
        { name: 'tana', hex: '#D9DCC1' },
        { name: 'link water', hex: '#D9E4F5' },
        { name: 'mabel', hex: '#D9F7FF' },
        { name: 'cerise', hex: '#DA3287' },
        { name: 'flame pea', hex: '#DA5B38' },
        { name: 'bamboo', hex: '#DA6304' },
        { name: 'red damask', hex: '#DA6A41' },
        { name: 'orchid', hex: '#DA70D6' },
        { name: 'copperfield', hex: '#DA8A67' },
        { name: 'golden grass', hex: '#DAA520' },
        { name: 'zanah', hex: '#DAECD6' },
        { name: 'iceberg', hex: '#DAF4F0' },
        { name: 'oyster bay', hex: '#DAFAFF' },
        { name: 'cranberry', hex: '#DB5079' },
        { name: 'petite orchid', hex: '#DB9690' },
        { name: 'di serria', hex: '#DB995E' },
        { name: 'alto', hex: '#DBDBDB' },
        { name: 'frosted mint', hex: '#DBFFF8' },
        { name: 'crimson', hex: '#DC143C' },
        { name: 'punch', hex: '#DC4333' },
        { name: 'galliano', hex: '#DCB20C' },
        { name: 'blossom', hex: '#DCB4BC' },
        { name: 'wattle', hex: '#DCD747' },
        { name: 'westar', hex: '#DCD9D2' },
        { name: 'moon mist', hex: '#DCDDCC' },
        { name: 'caper', hex: '#DCEDB4' },
        { name: 'swans down', hex: '#DCF0EA' },
        { name: 'swiss coffee', hex: '#DDD6D5' },
        { name: 'white ice', hex: '#DDF9F1' },
        { name: 'cerise red', hex: '#DE3163' },
        { name: 'roman', hex: '#DE6360' },
        { name: 'tumbleweed', hex: '#DEA681' },
        { name: 'gold tips', hex: '#DEBA13' },
        { name: 'brandy', hex: '#DEC196' },
        { name: 'wafer', hex: '#DECBC6' },
        { name: 'sapling', hex: '#DED4A4' },
        { name: 'barberry', hex: '#DED717' },
        { name: 'beryl green', hex: '#DEE5C0' },
        { name: 'pattens blue', hex: '#DEF5FF' },
        { name: 'heliotrope', hex: '#DF73FF' },
        { name: 'apache', hex: '#DFBE6F' },
        { name: 'chenin', hex: '#DFCD6F' },
        { name: 'lola', hex: '#DFCFDB' },
        { name: 'willow brook', hex: '#DFECDA' },
        { name: 'chartreuse yellow', hex: '#DFFF00' },
        { name: 'mauve', hex: '#E0B0FF' },
        { name: 'anzac', hex: '#E0B646' },
        { name: 'harvest gold', hex: '#E0B974' },
        { name: 'calico', hex: '#E0C095' },
        { name: 'baby blue', hex: '#E0FFFF' },
        { name: 'sunglo', hex: '#E16865' },
        { name: 'equator', hex: '#E1BC64' },
        { name: 'pink flare', hex: '#E1C0C8' },
        { name: 'periglacial blue', hex: '#E1E6D6' },
        { name: 'kidnapper', hex: '#E1EAD4' },
        { name: 'tara', hex: '#E1F6E8' },
        { name: 'mandy', hex: '#E25465' },
        { name: 'terracotta', hex: '#E2725B' },
        { name: 'golden bell', hex: '#E28913' },
        { name: 'shocking', hex: '#E292C0' },
        { name: 'dixie', hex: '#E29418' },
        { name: 'light orchid', hex: '#E29CD2' },
        { name: 'snuff', hex: '#E2D8ED' },
        { name: 'mystic', hex: '#E2EBED' },
        { name: 'apple green', hex: '#E2F3EC' },
        { name: 'razzmatazz', hex: '#E30B5C' },
        { name: 'alizarin crimson', hex: '#E32636' },
        { name: 'cinnabar', hex: '#E34234' },
        { name: 'cavern pink', hex: '#E3BEBE' },
        { name: 'peppermint', hex: '#E3F5E1' },
        { name: 'mindaro', hex: '#E3F988' },
        { name: 'deep blush', hex: '#E47698' },
        { name: 'gamboge', hex: '#E49B0F' },
        { name: 'melanie', hex: '#E4C2D5' },
        { name: 'twilight', hex: '#E4CFDE' },
        { name: 'bone', hex: '#E4D1C0' },
        { name: 'sunflower', hex: '#E4D422' },
        { name: 'grain brown', hex: '#E4D5B7' },
        { name: 'zombie', hex: '#E4D69B' },
        { name: 'frostee', hex: '#E4F6E7' },
        { name: 'snow flurry', hex: '#E4FFD1' },
        { name: 'amaranth', hex: '#E52B50' },
        { name: 'zest', hex: '#E5841B' },
        { name: 'dust storm', hex: '#E5CCC9' },
        { name: 'stark white', hex: '#E5D7BD' },
        { name: 'hampton', hex: '#E5D8AF' },
        { name: 'bon jour', hex: '#E5E0E1' },
        { name: 'mercury', hex: '#E5E5E5' },
        { name: 'polar', hex: '#E5F9F6' },
        { name: 'trinidad', hex: '#E64E03' },
        { name: 'gold sand', hex: '#E6BE8A' },
        { name: 'cashmere', hex: '#E6BEA5' },
        { name: 'double spanish white', hex: '#E6D7B9' },
        { name: 'satin linen', hex: '#E6E4D4' },
        { name: 'harp', hex: '#E6F2EA' },
        { name: 'off green', hex: '#E6F8F3' },
        { name: 'hint of green', hex: '#E6FFE9' },
        { name: 'tranquil', hex: '#E6FFFF' },
        { name: 'mango tango', hex: '#E77200' },
        { name: 'christine', hex: '#E7730A' },
        { name: 'tonys pink', hex: '#E79F8C' },
        { name: 'kobi', hex: '#E79FC4' },
        { name: 'rose fog', hex: '#E7BCB4' },
        { name: 'corn', hex: '#E7BF05' },
        { name: 'putty', hex: '#E7CD8C' },
        { name: 'gray nurse', hex: '#E7ECE6' },
        { name: 'lily white', hex: '#E7F8FF' },
        { name: 'bubbles', hex: '#E7FEFF' },
        { name: 'fire bush', hex: '#E89928' },
        { name: 'shilo', hex: '#E8B9B3' },
        { name: 'pearl bush', hex: '#E8E0D5' },
        { name: 'green white', hex: '#E8EBE0' },
        { name: 'chrome white', hex: '#E8F1D4' },
        { name: 'gin', hex: '#E8F2EB' },
        { name: 'aqua squeeze', hex: '#E8F5F2' },
        { name: 'clementine', hex: '#E96E00' },
        { name: 'burnt sienna', hex: '#E97451' },
        { name: 'tahiti gold', hex: '#E97C07' },
        { name: 'oyster pink', hex: '#E9CECD' },
        { name: 'confetti', hex: '#E9D75A' },
        { name: 'ebb', hex: '#E9E3E3' },
        { name: 'ottoman', hex: '#E9F8ED' },
        { name: 'clear day', hex: '#E9FFFD' },
        { name: 'carissma', hex: '#EA88A8' },
        { name: 'porsche', hex: '#EAAE69' },
        { name: 'tulip tree', hex: '#EAB33B' },
        { name: 'rob roy', hex: '#EAC674' },
        { name: 'raffia', hex: '#EADAB8' },
        { name: 'white rock', hex: '#EAE8D4' },
        { name: 'panache', hex: '#EAF6EE' },
        { name: 'solitude', hex: '#EAF6FF' },
        { name: 'aqua spring', hex: '#EAF9F5' },
        { name: 'dew', hex: '#EAFFFE' },
        { name: 'apricot', hex: '#EB9373' },
        { name: 'zinnwaldite', hex: '#EBC2AF' },
        { name: 'fuel yellow', hex: '#ECA927' },
        { name: 'ronchi', hex: '#ECC54E' },
        { name: 'french lilac', hex: '#ECC7EE' },
        { name: 'just right', hex: '#ECCDB9' },
        { name: 'wild rice', hex: '#ECE090' },
        { name: 'fall green', hex: '#ECEBBD' },
        { name: 'aths special', hex: '#ECEBCE' },
        { name: 'starship', hex: '#ECF245' },
        { name: 'red ribbon', hex: '#ED0A3F' },
        { name: 'tango', hex: '#ED7A1C' },
        { name: 'carrot orange', hex: '#ED9121' },
        { name: 'sea pink', hex: '#ED989E' },
        { name: 'tacao', hex: '#EDB381' },
        { name: 'desert sand', hex: '#EDC9AF' },
        { name: 'pancho', hex: '#EDCDAB' },
        { name: 'chamois', hex: '#EDDCB1' },
        { name: 'primrose', hex: '#EDEA99' },
        { name: 'frost', hex: '#EDF5DD' },
        { name: 'aqua haze', hex: '#EDF5F5' },
        { name: 'zumthor', hex: '#EDF6FF' },
        { name: 'narvik', hex: '#EDF9F1' },
        { name: 'honeysuckle', hex: '#EDFC84' },
        { name: 'lavender magenta', hex: '#EE82EE' },
        { name: 'beauty bush', hex: '#EEC1BE' },
        { name: 'chalky', hex: '#EED794' },
        { name: 'almond', hex: '#EED9C4' },
        { name: 'flax', hex: '#EEDC82' },
        { name: 'bizarre', hex: '#EEDEDA' },
        { name: 'double colonial white', hex: '#EEE3AD' },
        { name: 'cararra', hex: '#EEEEE8' },
        { name: 'manz', hex: '#EEEF78' },
        { name: 'tahuna sands', hex: '#EEF0C8' },
        { name: 'athens gray', hex: '#EEF0F3' },
        { name: 'tusk', hex: '#EEF3C3' },
        { name: 'loafer', hex: '#EEF4DE' },
        { name: 'catskill white', hex: '#EEF6F7' },
        { name: 'twilight blue', hex: '#EEFDFF' },
        { name: 'jonquil', hex: '#EEFF9A' },
        { name: 'rice flower', hex: '#EEFFE2' },
        { name: 'jaffa', hex: '#EF863F' },
        { name: 'gallery', hex: '#EFEFEF' },
        { name: 'porcelain', hex: '#EFF2F3' },
        { name: 'mauvelous', hex: '#F091A9' },
        { name: 'golden dream', hex: '#F0D52D' },
        { name: 'golden sand', hex: '#F0DB7D' },
        { name: 'buff', hex: '#F0DC82' },
        { name: 'prim', hex: '#F0E2EC' },
        { name: 'khaki', hex: '#F0E68C' },
        { name: 'selago', hex: '#F0EEFD' },
        { name: 'titan white', hex: '#F0EEFF' },
        { name: 'alice blue', hex: '#F0F8FF' },
        { name: 'feta', hex: '#F0FCEA' },
        { name: 'gold drop', hex: '#F18200' },
        { name: 'wewak', hex: '#F19BAB' },
        { name: 'sahara sand', hex: '#F1E788' },
        { name: 'parchment', hex: '#F1E9D2' },
        { name: 'blue chalk', hex: '#F1E9FF' },
        { name: 'mint julep', hex: '#F1EEC1' },
        { name: 'seashell', hex: '#F1F1F1' },
        { name: 'saltpan', hex: '#F1F7F2' },
        { name: 'tidal', hex: '#F1FFAD' },
        { name: 'chiffon', hex: '#F1FFC8' },
        { name: 'flamingo', hex: '#F2552A' },
        { name: 'tangerine', hex: '#F28500' },
        { name: 'mandys pink', hex: '#F2C3B2' },
        { name: 'concrete', hex: '#F2F2F2' },
        { name: 'black squeeze', hex: '#F2FAFA' },
        { name: 'pomegranate', hex: '#F34723' },
        { name: 'buttercup', hex: '#F3AD16' },
        { name: 'new orleans', hex: '#F3D69D' },
        { name: 'vanilla ice', hex: '#F3D9DF' },
        { name: 'sidecar', hex: '#F3E7BB' },
        { name: 'dawn pink', hex: '#F3E9E5' },
        { name: 'wheatfield', hex: '#F3EDCF' },
        { name: 'canary', hex: '#F3FB62' },
        { name: 'orinoco', hex: '#F3FBD4' },
        { name: 'carla', hex: '#F3FFD8' },
        { name: 'hollywood cerise', hex: '#F400A1' },
        { name: 'sandy brown', hex: '#F4A460' },
        { name: 'saffron', hex: '#F4C430' },
        { name: 'ripe lemon', hex: '#F4D81C' },
        { name: 'janna', hex: '#F4EBD3' },
        { name: 'pampas', hex: '#F4F2EE' },
        { name: 'wild sand', hex: '#F4F4F4' },
        { name: 'zircon', hex: '#F4F8FF' },
        { name: 'froly', hex: '#F57584' },
        { name: 'cream can', hex: '#F5C85C' },
        { name: 'manhattan', hex: '#F5C999' },
        { name: 'maize', hex: '#F5D5A0' },
        { name: 'wheat', hex: '#F5DEB3' },
        { name: 'sandwisp', hex: '#F5E7A2' },
        { name: 'pot pourri', hex: '#F5E7E2' },
        { name: 'albescent white', hex: '#F5E9D3' },
        { name: 'soft peach', hex: '#F5EDEF' },
        { name: 'ecru white', hex: '#F5F3E5' },
        { name: 'beige', hex: '#F5F5DC' },
        { name: 'golden fizz', hex: '#F5FB3D' },
        { name: 'australian mint', hex: '#F5FFBE' },
        { name: 'french rose', hex: '#F64A8A' },
        { name: 'brilliant rose', hex: '#F653A6' },
        { name: 'illusion', hex: '#F6A4C9' },
        { name: 'merino', hex: '#F6F0E6' },
        { name: 'black haze', hex: '#F6F7F7' },
        { name: 'spring sun', hex: '#F6FFDC' },
        { name: 'violet red', hex: '#F7468A' },
        { name: 'chilean fire', hex: '#F77703' },
        { name: 'persian pink', hex: '#F77FBE' },
        { name: 'rajah', hex: '#F7B668' },
        { name: 'azalea', hex: '#F7C8DA' },
        { name: 'we peep', hex: '#F7DBE6' },
        { name: 'quarter spanish white', hex: '#F7F2E1' },
        { name: 'whisper', hex: '#F7F5FA' },
        { name: 'snow drift', hex: '#F7FAF7' },
        { name: 'casablanca', hex: '#F8B853' },
        { name: 'chantilly', hex: '#F8C3DF' },
        { name: 'cherub', hex: '#F8D9E9' },
        { name: 'marzipan', hex: '#F8DB9D' },
        { name: 'energy yellow', hex: '#F8DD5C' },
        { name: 'givry', hex: '#F8E4BF' },
        { name: 'white linen', hex: '#F8F0E8' },
        { name: 'magnolia', hex: '#F8F4FF' },
        { name: 'spring wood', hex: '#F8F6F1' },
        { name: 'coconut cream', hex: '#F8F7DC' },
        { name: 'white lilac', hex: '#F8F7FC' },
        { name: 'desert storm', hex: '#F8F8F7' },
        { name: 'texas', hex: '#F8F99C' },
        { name: 'corn field', hex: '#F8FACD' },
        { name: 'mimosa', hex: '#F8FDD3' },
        { name: 'carnation', hex: '#F95A61' },
        { name: 'saffron mango', hex: '#F9BF58' },
        { name: 'carousel pink', hex: '#F9E0ED' },
        { name: 'dairy cream', hex: '#F9E4BC' },
        { name: 'portica', hex: '#F9E663' },
        { name: 'amour', hex: '#F9EAF3' },
        { name: 'rum swizzle', hex: '#F9F8E4' },
        { name: 'dolly', hex: '#F9FF8B' },
        { name: 'sugar cane', hex: '#F9FFF6' },
        { name: 'ecstasy', hex: '#FA7814' },
        { name: 'tan hide', hex: '#FA9D5A' },
        { name: 'corvette', hex: '#FAD3A2' },
        { name: 'peach yellow', hex: '#FADFAD' },
        { name: 'turbo', hex: '#FAE600' },
        { name: 'astra', hex: '#FAEAB9' },
        { name: 'champagne', hex: '#FAECCC' },
        { name: 'linen', hex: '#FAF0E6' },
        { name: 'fantasy', hex: '#FAF3F0' },
        { name: 'citrine white', hex: '#FAF7D6' },
        { name: 'alabaster', hex: '#FAFAFA' },
        { name: 'hint of yellow', hex: '#FAFDE4' },
        { name: 'milan', hex: '#FAFFA4' },
        { name: 'brink pink', hex: '#FB607F' },
        { name: 'geraldine', hex: '#FB8989' },
        { name: 'lavender rose', hex: '#FBA0E3' },
        { name: 'sea buckthorn', hex: '#FBA129' },
        { name: 'sun', hex: '#FBAC13' },
        { name: 'lavender pink', hex: '#FBAED2' },
        { name: 'rose bud', hex: '#FBB2A3' },
        { name: 'cupid', hex: '#FBBEDA' },
        { name: 'classic rose', hex: '#FBCCE7' },
        { name: 'apricot peach', hex: '#FBCEB1' },
        { name: 'banana mania', hex: '#FBE7B2' },
        { name: 'marigold yellow', hex: '#FBE870' },
        { name: 'festival', hex: '#FBE96C' },
        { name: 'sweet corn', hex: '#FBEA8C' },
        { name: 'candy corn', hex: '#FBEC5D' },
        { name: 'hint of red', hex: '#FBF9F9' },
        { name: 'shalimar', hex: '#FBFFBA' },
        { name: 'shocking pink', hex: '#FC0FC0' },
        { name: 'tickle me pink', hex: '#FC80A5' },
        { name: 'tree poppy', hex: '#FC9C1D' },
        { name: 'lightning yellow', hex: '#FCC01E' },
        { name: 'goldenrod', hex: '#FCD667' },
        { name: 'candlelight', hex: '#FCD917' },
        { name: 'cherokee', hex: '#FCDA98' },
        { name: 'double pearl lusta', hex: '#FCF4D0' },
        { name: 'pearl lusta', hex: '#FCF4DC' },
        { name: 'vista white', hex: '#FCF8F7' },
        { name: 'bianca', hex: '#FCFBF3' },
        { name: 'moon glow', hex: '#FCFEDA' },
        { name: 'china ivory', hex: '#FCFFE7' },
        { name: 'ceramic', hex: '#FCFFF9' },
        { name: 'torch red', hex: '#FD0E35' },
        { name: 'wild watermelon', hex: '#FD5B78' },
        { name: 'crusta', hex: '#FD7B33' },
        { name: 'sorbus', hex: '#FD7C07' },
        { name: 'sweet pink', hex: '#FD9FA2' },
        { name: 'light apricot', hex: '#FDD5B1' },
        { name: 'pig pink', hex: '#FDD7E4' },
        { name: 'cinderella', hex: '#FDE1DC' },
        { name: 'golden glow', hex: '#FDE295' },
        { name: 'lemon', hex: '#FDE910' },
        { name: 'old lace', hex: '#FDF5E6' },
        { name: 'half colonial white', hex: '#FDF6D3' },
        { name: 'drover', hex: '#FDF7AD' },
        { name: 'pale prim', hex: '#FDFEB8' },
        { name: 'cumulus', hex: '#FDFFD5' },
        { name: 'persian rose', hex: '#FE28A2' },
        { name: 'sunset orange', hex: '#FE4C40' },
        { name: 'bittersweet', hex: '#FE6F5E' },
        { name: 'california', hex: '#FE9D04' },
        { name: 'yellow sea', hex: '#FEA904' },
        { name: 'melon', hex: '#FEBAAD' },
        { name: 'bright sun', hex: '#FED33C' },
        { name: 'dandelion', hex: '#FED85D' },
        { name: 'salomie', hex: '#FEDB8D' },
        { name: 'cape honey', hex: '#FEE5AC' },
        { name: 'remy', hex: '#FEEBF3' },
        { name: 'oasis', hex: '#FEEFCE' },
        { name: 'bridesmaid', hex: '#FEF0EC' },
        { name: 'beeswax', hex: '#FEF2C7' },
        { name: 'bleach white', hex: '#FEF3D8' },
        { name: 'pipi', hex: '#FEF4CC' },
        { name: 'half spanish white', hex: '#FEF4DB' },
        { name: 'wisp pink', hex: '#FEF4F8' },
        { name: 'provincial pink', hex: '#FEF5F1' },
        { name: 'half dutch white', hex: '#FEF7DE' },
        { name: 'solitaire', hex: '#FEF8E2' },
        { name: 'white pointer', hex: '#FEF8FF' },
        { name: 'off yellow', hex: '#FEF9E3' },
        { name: 'orange white', hex: '#FEFCED' },
        { name: 'red', hex: '#FF0000' },
        { name: 'rose', hex: '#FF007F' },
        { name: 'purple pizzazz', hex: '#FF00CC' },
        { name: 'magenta / fuchsia', hex: '#FF00FF' },
        { name: 'scarlet', hex: '#FF2400' },
        { name: 'wild strawberry', hex: '#FF3399' },
        { name: 'razzle dazzle rose', hex: '#FF33CC' },
        { name: 'radical red', hex: '#FF355E' },
        { name: 'red orange', hex: '#FF3F34' },
        { name: 'coral red', hex: '#FF4040' },
        { name: 'vermilion', hex: '#FF4D00' },
        { name: 'international orange', hex: '#FF4F00' },
        { name: 'outrageous orange', hex: '#FF6037' },
        { name: 'blaze orange', hex: '#FF6600' },
        { name: 'pink flamingo', hex: '#FF66FF' },
        { name: 'orange', hex: '#FF681F' },
        { name: 'hot pink', hex: '#FF69B4' },
        { name: 'persimmon', hex: '#FF6B53' },
        { name: 'blush pink', hex: '#FF6FFF' },
        { name: 'burning orange', hex: '#FF7034' },
        { name: 'pumpkin', hex: '#FF7518' },
        { name: 'flamenco', hex: '#FF7D07' },
        { name: 'flush orange', hex: '#FF7F00' },
        { name: 'coral', hex: '#FF7F50' },
        { name: 'salmon', hex: '#FF8C69' },
        { name: 'pizazz', hex: '#FF9000' },
        { name: 'west side', hex: '#FF910F' },
        { name: 'pink salmon', hex: '#FF91A4' },
        { name: 'neon carrot', hex: '#FF9933' },
        { name: 'atomic tangerine', hex: '#FF9966' },
        { name: 'vivid tangerine', hex: '#FF9980' },
        { name: 'sunshade', hex: '#FF9E2C' },
        { name: 'orange peel', hex: '#FFA000' },
        { name: 'mona lisa', hex: '#FFA194' },
        { name: 'web orange', hex: '#FFA500' },
        { name: 'carnation pink', hex: '#FFA6C9' },
        { name: 'hit pink', hex: '#FFAB81' },
        { name: 'yellow orange', hex: '#FFAE42' },
        { name: 'cornflower lilac', hex: '#FFB0AC' },
        { name: 'sundown', hex: '#FFB1B3' },
        { name: 'my sin', hex: '#FFB31F' },
        { name: 'texas rose', hex: '#FFB555' },
        { name: 'cotton candy', hex: '#FFB7D5' },
        { name: 'macaroni and cheese', hex: '#FFB97B' },
        { name: 'selective yellow', hex: '#FFBA00' },
        { name: 'koromiko', hex: '#FFBD5F' },
        { name: 'amber', hex: '#FFBF00' },
        { name: 'wax flower', hex: '#FFC0A8' },
        { name: 'pink', hex: '#FFC0CB' },
        { name: 'your pink', hex: '#FFC3C0' },
        { name: 'supernova', hex: '#FFC901' },
        { name: 'flesh', hex: '#FFCBA4' },
        { name: 'sunglow', hex: '#FFCC33' },
        { name: 'golden tainoi', hex: '#FFCC5C' },
        { name: 'peach orange', hex: '#FFCC99' },
        { name: 'chardonnay', hex: '#FFCD8C' },
        { name: 'pastel pink', hex: '#FFD1DC' },
        { name: 'romantic', hex: '#FFD2B7' },
        { name: 'grandis', hex: '#FFD38C' },
        { name: 'gold', hex: '#FFD700' },
        { name: 'school bus yellow', hex: '#FFD800' },
        { name: 'cosmos', hex: '#FFD8D9' },
        { name: 'mustard', hex: '#FFDB58' },
        { name: 'peach schnapps', hex: '#FFDCD6' },
        { name: 'caramel', hex: '#FFDDAF' },
        { name: 'tuft bush', hex: '#FFDDCD' },
        { name: 'watusi', hex: '#FFDDCF' },
        { name: 'pink lace', hex: '#FFDDF4' },
        { name: 'navajo white', hex: '#FFDEAD' },
        { name: 'frangipani', hex: '#FFDEB3' },
        { name: 'pippin', hex: '#FFE1DF' },
        { name: 'pale rose', hex: '#FFE1F2' },
        { name: 'negroni', hex: '#FFE2C5' },
        { name: 'cream brulee', hex: '#FFE5A0' },
        { name: 'peach', hex: '#FFE5B4' },
        { name: 'tequila', hex: '#FFE6C7' },
        { name: 'kournikova', hex: '#FFE772' },
        { name: 'sandy beach', hex: '#FFEAC8' },
        { name: 'karry', hex: '#FFEAD4' },
        { name: 'broom', hex: '#FFEC13' },
        { name: 'colonial white', hex: '#FFEDBC' },
        { name: 'derby', hex: '#FFEED8' },
        { name: 'vis vis', hex: '#FFEFA1' },
        { name: 'egg white', hex: '#FFEFC1' },
        { name: 'papaya whip', hex: '#FFEFD5' },
        { name: 'fair pink', hex: '#FFEFEC' },
        { name: 'peach cream', hex: '#FFF0DB' },
        { name: 'lavender blush', hex: '#FFF0F5' },
        { name: 'gorse', hex: '#FFF14F' },
        { name: 'buttermilk', hex: '#FFF1B5' },
        { name: 'pink lady', hex: '#FFF1D8' },
        { name: 'forget me not', hex: '#FFF1EE' },
        { name: 'tutu', hex: '#FFF1F9' },
        { name: 'picasso', hex: '#FFF39D' },
        { name: 'chardon', hex: '#FFF3F1' },
        { name: 'paris daisy', hex: '#FFF46E' },
        { name: 'barley white', hex: '#FFF4CE' },
        { name: 'egg sour', hex: '#FFF4DD' },
        { name: 'sazerac', hex: '#FFF4E0' },
        { name: 'serenade', hex: '#FFF4E8' },
        { name: 'chablis', hex: '#FFF4F3' },
        { name: 'seashell peach', hex: '#FFF5EE' },
        { name: 'sauvignon', hex: '#FFF5F3' },
        { name: 'milk punch', hex: '#FFF6D4' },
        { name: 'varden', hex: '#FFF6DF' },
        { name: 'rose white', hex: '#FFF6F5' },
        { name: 'baja white', hex: '#FFF8D1' },
        { name: 'gin fizz', hex: '#FFF9E2' },
        { name: 'early dawn', hex: '#FFF9E6' },
        { name: 'lemon chiffon', hex: '#FFFACD' },
        { name: 'bridal heath', hex: '#FFFAF4' },
        { name: 'scotch mist', hex: '#FFFBDC' },
        { name: 'soapstone', hex: '#FFFBF9' },
        { name: 'witch haze', hex: '#FFFC99' },
        { name: 'buttery white', hex: '#FFFCEA' },
        { name: 'island spice', hex: '#FFFCEE' },
        { name: 'cream', hex: '#FFFDD0' },
        { name: 'chilean heath', hex: '#FFFDE6' },
        { name: 'travertine', hex: '#FFFDE8' },
        { name: 'orchid white', hex: '#FFFDF3' },
        { name: 'quarter pearl lusta', hex: '#FFFDF4' },
        { name: 'half and half', hex: '#FFFEE1' },
        { name: 'apricot white', hex: '#FFFEEC' },
        { name: 'rice cake', hex: '#FFFEF0' },
        { name: 'black white', hex: '#FFFEF6' },
        { name: 'romance', hex: '#FFFEFD' },
        { name: 'yellow', hex: '#FFFF00' },
        { name: 'laser lemon', hex: '#FFFF66' },
        { name: 'pale canary', hex: '#FFFF99' },
        { name: 'portafino', hex: '#FFFFB4' },
        { name: 'ivory', hex: '#FFFFF0' },
        { name: 'white', hex: '#FFFFFF' }
      ]
    end
  end
end
