# frozen_string_literal: true

module ColorSwatchCollection
  class Pantone
    def self.colours
      [
        { name: 'mahogany', hex: '#CD4A4A' },
        { name: 'fuzzy wuzzy brown', hex: '#CC6666' },
        { name: 'chestnut', hex: '#BC5D58' },
        { name: 'red orange', hex: '#FF5349' },
        { name: 'sunset orange', hex: '#FD5E53' },
        { name: 'bittersweet', hex: '#FD7C6E' },
        { name: 'melon', hex: '#FDBCB4' },
        { name: 'outrageous orange', hex: '#FF6E4A' },
        { name: 'vivid tangerine', hex: '#FFA089' },
        { name: 'burnt sienna', hex: '#EA7E5D' },
        { name: 'brown', hex: '#B4674D' },
        { name: 'sepia', hex: '#A5694F' },
        { name: 'orange', hex: '#FF7538' },
        { name: 'burnt orange', hex: '#FF7F49' },
        { name: 'copper', hex: '#DD9475' },
        { name: 'mango tango', hex: '#FF8243' },
        { name: 'atomic tangerine', hex: '#FFA474' },
        { name: 'beaver', hex: '#9F8170' },
        { name: 'antique brass', hex: '#CD9575' },
        { name: 'desert sand', hex: '#EFCDB8' },
        { name: 'raw sienna', hex: '#D68A59' },
        { name: 'tumbleweed', hex: '#DEAA88' },
        { name: 'tan', hex: '#FAA76C' },
        { name: 'peach', hex: '#FFCFAB' },
        { name: 'macaroni and cheese', hex: '#FFBD88' },
        { name: 'apricot', hex: '#FDD9B5' },
        { name: 'neon carrot', hex: '#FFA343' },
        { name: 'almond', hex: '#EFDBC5' },
        { name: 'yellow orange', hex: '#FFB653' },
        { name: 'gold', hex: '#E7C697' },
        { name: 'shadow', hex: '#8A795D' },
        { name: 'banana mania', hex: '#FAE7B5' },
        { name: 'sunglow', hex: '#FFCF48' },
        { name: 'goldenrod', hex: '#FCD975' },
        { name: 'dandelion', hex: '#FDDB6D' },
        { name: 'yellow', hex: '#FCE883' },
        { name: 'green yellow', hex: '#F0E891' },
        { name: 'spring green', hex: '#ECEABE' },
        { name: 'olive green', hex: '#BAB86C' },
        { name: 'laser lemon', hex: '#FDFC74' },
        { name: 'unmellow yellow', hex: '#FDFC74' },
        { name: 'canary', hex: '#FFFF99' },
        { name: 'yellow green', hex: '#C5E384' },
        { name: 'inch worm', hex: '#B2EC5D' },
        { name: 'asparagus', hex: '#87A96B' },
        { name: 'granny smith apple', hex: '#A8E4A0' },
        { name: 'electric lime', hex: '#1DF914' },
        { name: 'screamin green', hex: '#76FF7A' },
        { name: 'fern', hex: '#71BC78' },
        { name: 'forest green', hex: '#6DAE81' },
        { name: 'sea green', hex: '#9FE2BF' },
        { name: 'green', hex: '#1CAC78' },
        { name: 'mountain meadow', hex: '#30BA8F' },
        { name: 'shamrock', hex: '#45CEA2' },
        { name: 'jungle green', hex: '#3BB08F' },
        { name: 'caribbean green', hex: '#1CD3A2' },
        { name: 'tropical rain forest', hex: '#17806D' },
        { name: 'pine green', hex: '#158078' },
        { name: 'robin egg blue', hex: '#1FCECB' },
        { name: 'aquamarine', hex: '#78DBE2' },
        { name: 'turquoise blue', hex: '#77DDE7' },
        { name: 'sky blue', hex: '#80DAEB' },
        { name: 'outer space', hex: '#414A4C' },
        { name: 'blue green', hex: '#199EBD' },
        { name: 'pacific blue', hex: '#1CA9C9' },
        { name: 'cerulean', hex: '#1DACD6' },
        { name: 'cornflower', hex: '#9ACEEB' },
        { name: 'midnight blue', hex: '#1A4876' },
        { name: 'navy blue', hex: '#1974D2' },
        { name: 'denim', hex: '#2B6CC4' },
        { name: 'blue', hex: '#1F75FE' },
        { name: 'periwinkle', hex: '#C5D0E6' },
        { name: 'cadet blue', hex: '#B0B7C6' },
        { name: 'indigo', hex: '#5D76CB' },
        { name: 'wild blue yonder', hex: '#A2ADD0' },
        { name: 'manatee', hex: '#979AAA' },
        { name: 'blue bell', hex: '#ADADD6' },
        { name: 'blue violet', hex: '#7366BD' },
        { name: 'purple heart', hex: '#7442C8' },
        { name: 'royal purple', hex: '#7851A9' },
        { name: 'purple mountains’ majesty', hex: '#9D81BA' },
        { name: 'violet (purple)', hex: '#926EAE' },
        { name: 'wisteria', hex: '#CDA4DE' },
        { name: 'vivid violet', hex: '#8F509D' },
        { name: 'fuchsia', hex: '#C364C5' },
        { name: 'shocking pink', hex: '#FB7EFD' },
        { name: 'pink flamingo', hex: '#FC74FD' },
        { name: 'plum', hex: '#8E4585' },
        { name: 'hot magenta', hex: '#FF1DCE' },
        { name: 'purple pizzazz', hex: '#FF1DCE' },
        { name: 'razzle dazzle rose', hex: '#FF48D0' },
        { name: 'orchid', hex: '#E6A8D7' },
        { name: 'red violet', hex: '#C0448F' },
        { name: 'eggplant', hex: '#6E5160' },
        { name: 'cerise', hex: '#DD4492' },
        { name: 'wild strawberry', hex: '#FF43A4' },
        { name: 'magenta', hex: '#F664AF' },
        { name: 'lavender', hex: '#FCB4D5' },
        { name: 'cotton candy', hex: '#FFBCD9' },
        { name: 'violet red', hex: '#F75394' },
        { name: 'carnation pink', hex: '#FFAACC' },
        { name: 'razzmatazz', hex: '#E3256B' },
        { name: 'piggy pink', hex: '#FDD7E4' },
        { name: 'jazzberry jam', hex: '#CA3767' },
        { name: 'blush', hex: '#DE5D83' },
        { name: 'tickle me pink', hex: '#FC89AC' },
        { name: 'pink sherbet', hex: '#F780A1' },
        { name: 'maroon', hex: '#C8385A' },
        { name: 'red', hex: '#EE204D' },
        { name: 'radical red', hex: '#FF496C' },
        { name: 'mauvelous', hex: '#EF98AA' },
        { name: 'wild watermelon', hex: '#FC6C85' },
        { name: 'scarlet', hex: '#FC2847' },
        { name: 'salmon', hex: '#FF9BAA' },
        { name: 'brick red', hex: '#CB4154' },
        { name: 'white', hex: '#EDEDED' },
        { name: 'timberwolf', hex: '#DBD7D2' },
        { name: 'silver', hex: '#CDC5C2' },
        { name: 'gray', hex: '#95918C' },
        { name: 'black', hex: '#232323' }
      ]
    end
  end
end
